In [0]:
import tensorflow as tf
import numpy as np

In [0]:
arr = np.random.randint(low=2, high=200, size=60)
arr1 = arr.reshape((10,6))
arr2 = arr.reshape((5,4,3))

In [0]:
arr2

array([[[ 59, 172, 118],
        [ 68,  73, 117],
        [147, 160,  22],
        [175, 148,  47]],

       [[  4, 154, 109],
        [178, 182, 168],
        [ 62, 131,  16],
        [112,  15,  12]],

       [[ 90,  54, 135],
        [  2,  77, 128],
        [ 95,  60,  94],
        [ 12,  68,  30]],

       [[ 68, 178, 158],
        [142, 119,  35],
        [183, 112,  26],
        [ 22,  67,  37]],

       [[136, 125,  78],
        [  3, 120, 106],
        [115, 128, 140],
        [120, 168, 146]]])

In [0]:
arr1

array([[175,  92, 190,  37, 123,  62],
       [ 87,  36,  91,  72,  25, 102],
       [135,  94,   2,  31,  36,  63],
       [ 92, 131, 116, 191,  94,  81],
       [ 53,  94, 173,  75,   2, 143],
       [165, 178, 146,  40,  61,  31],
       [  9, 172,  63, 193,  34, 191],
       [137, 189, 135, 193, 109,  99],
       [ 31,  93, 160,  83, 119, 147],
       [163, 153, 198,  91,  26, 182]])

In [0]:
t1 = tf.constant(value=arr, dtype=tf.int32)

In [0]:
tlu1 = tf.nn.embedding_lookup(params=arr1, ids=[2, 4, 1, 5])
tlu2 = tf.nn.embedding_lookup(params=arr1, ids=[[1, 2]])
tlu3 = tf.nn.embedding_lookup(params=arr1, ids=[[1], [2]])
tlu4 = tf.nn.embedding_lookup(params=arr2, ids=[2, 3])
tlu5 = tf.nn.embedding_lookup(params=arr2, ids=[[2], [3]])

In [0]:
with tf.Session() as sess:
  # print(sess.run(tlu1))
  # print(sess.run(tlu2))
  # print(sess.run(tlu3))
  # print(sess.run(tlu4))
  print(sess.run(tlu5))

[[[[ 90  54 135]
   [  2  77 128]
   [ 95  60  94]
   [ 12  68  30]]]


 [[[ 68 178 158]
   [142 119  35]
   [183 112  26]
   [ 22  67  37]]]]
