In [0]:
import tensorflow as tf
import numpy as np

In [0]:
arr1 = np.array([(1, 2, 3), (4, 5, 6)])
a = tf.constant(value=arr1)
b = tf.placeholder(shape=(3, 2), dtype='int32')
c = tf.Variable(initial_value=arr1)

In [0]:
# initializer
init = tf.global_variables_initializer()

In [0]:
with tf.Session() as sess:
  # without this, variable will not run
  sess.run(init)
  c = tf.reshape(tensor=c, shape=[-1])
  print(sess.run(a))
  print(sess.run(c))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
