In [2]:
import numpy as np
import tensorflow as tf

In [56]:
arr1 = np.array([([(1, 2, 3), (4, 5, 6)]), ([(7, 8, 9), (11, 12, 16)])], dtype='float32')
arr2 = np.array([([(11, 12, 16), (7, 8, 9)]), ([(4, 5, 6), (1, 2, 3)])])
arr3 = np.arange(10)
print(arr1)
print(arr2)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 16.]]]
[[[11 12 16]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 1  2  3]]]


In [0]:
a0 = tf.constant(value=arr1, dtype='float32')
b0 = tf.constant(value=arr2)
a = tf.Variable(initial_value=arr1, name="a", validate_shape=True)
b = tf.Variable(initial_value=arr2, name="b", validate_shape=False)

In [5]:
print(a.shape)
print(a.dtype)
print(a.graph)
print(a.initial_value)
print(a.name)
# print(a.op)

(2, 2, 3)
<dtype: 'int64_ref'>
Tensor("a/initial_value:0", shape=(2, 2, 3), dtype=int64)
a:0


In [41]:
mat1 = np.array([(1, 2, 3), (4, 5, 6)])
mat2 = np.array([(1, 2), (3, 4), (5, 6)])
mat3 = mat1 @ mat2
print(mat3)
c = tf.matmul(a=mat1, b=mat2, name="MatrixMultiplication1")
d = tf.matmul(a=mat2, b=mat1, name="MatrixMultiplication2")

[[22 28]
 [49 64]]


In [0]:
# Will not run when we use variables a and b instead of constants
e = tf.concat(values=[a0, b0], axis=0)
f = tf.concat(values=[arr1, arr2], axis=1)
g = tf.concat(values=[arr1, arr2], axis=2)

In [0]:
arr4 = np.array([1, 2, 4], dtype='float32')

# does not work with variables
h = tf.constant(value=arr4)

# works well for arrays and 1D tensors
i = tf.norm(arr4)
j = tf.norm(h)

# works well with 2D arrays and tensors
k = tf.norm(arr1)
l = tf.norm(a0)

In [0]:
m = tf.linspace(start=60.0, stop=72.0, num=7)
m0 = tf.linspace(start=0.0, stop=10.0, num=11)
m1 = np.arange(10)

# Given N one-dimensional coordinate arrays *args,
# returns a list outputs of N-D coordinate arrays 
# for evaluating expressions on an N-D grid.
n = tf.meshgrid(m1, m1)
o = tf.meshgrid(m0, m0)

In [107]:
print(b0.shape)
b00 = tf.reshape(b0, (1, 2, 6))
b01 = tf.reshape(b0, [-1])
b02 = tf.reshape(b0, [1, 4, 3])
print(b0.shape)
print(b00.shape)
print(b01.shape)
print(b02.shape)

(2, 2, 3)
(2, 2, 3)
(1, 2, 6)
(12,)
(1, 4, 3)


In [121]:
def tanh_sigmoid(x):
  return np.tanh(x)

tanh_sigmoid([1, 2, 3])
# p = tf.numpy_function(func=tanh_sigmoid, inp=[[1, 2, 3]], Tout='double')

array([0.76159416, 0.96402758, 0.99505475])

In [120]:
with tf.Session() as sess:
  # print(sess.run(b0))
  # print(sess.run(b01))
  # print(sess.run(b02))
  # print(sess.run(b00))
  # print(sess.run(c))
  # print(sess.run(d))
  # print(sess.run(e))
  # print(sess.run(f))
  # print(sess.run(g))
  # print(sess.run(h))
  # print(sess.run(i))
  # print(sess.run(j))
  # print(sess.run(k))
  # print(sess.run(l))
  # print(sess.run(m))
  # print(sess.run(n))
  # print(sess.run(o))
  print(sess.run(p))

[0.76159416 0.96402758 0.99505475]
