In [0]:
import pandas as pd

In [0]:
import tensorflow as tf

In [0]:
tf.__version__
import numpy as np

In [0]:
arr1 = np.array([([(1, 2, 3), (4, 5, 6)]), ([(7, 8, 9), (11, 12, 16)])])
print(arr1.shape)
print(arr1.ndim)
print(arr1)

(2, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 16]]]


In [0]:
arr1.sum(axis=2)

array([[ 6, 15],
       [24, 39]])

In [0]:
np.take(arr1, 0, axis=1)

array([[1, 2, 3],
       [7, 8, 9]])

In [0]:
# creates a Const node in the computation graph 
# with the exact value at graph construction time
a = tf.constant(value=arr1)

In [0]:
b = tf.placeholder(dtype='int64')

In [0]:
c = tf.range(start=3, limit=18, delta=2)

In [0]:
rank = tf.rank(arr1)

In [0]:
with tf.Session() as sess:
  print(sess.run(rank))
  print(sess.run(c))
  print(sess.run(a))